# Examen Final - Recuperación de Información
---

In [ ]:
! pip install rank_bm25 sentence-transformers faiss-cpu transformers
! pip install nltk
import nltk
nltk.download('punkt')
nltk.download('stopwords')

Collecting rank_bm25
  Downloading rank_bm25-0.2.2-py3-none-any.whl.metadata (3.2 kB)
Collecting sentence-transformers
  Downloading sentence_transformers-5.0.0-py3-none-any.whl.metadata (16 kB)
Collecting faiss-cpu
  Downloading faiss_cpu-1.11.0.post1-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Collecting transformers
  Downloading transformers-4.54.0-py3-none-any.whl.metadata (41 kB)
Collecting numpy (from rank_bm25)
  Downloading numpy-2.3.2-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting tqdm (from sentence-transformers)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting torch>=1.11.0 (from sentence-transformers)
  Downloading torch-2.7.1-cp312-cp312-win_amd64.whl.metadata (28 kB)
Collecting scikit-learn (from sentence-transformers)
  Downloading scikit_learn-1.7.1-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting scipy (from sentence-transformers)
  Downloading scipy-1.16.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers)
  Downloading huggingface_hub-0.34.2-py3-none-any.whl.metadata (14 kB)
Collecting Pillow (from sentence-transformers)
  Downloading pillow-11.3.0-cp312-cp312-win_amd64.whl.metadata (9.2 kB)
Collecting typing_extensions>=4.5.0 (from sentence-transformers)
  Downloading typing_extensions-4.14.1-py3-none-any.whl.metadata (3.0 kB)
Collecting filelock (from transformers)
  Downloading filelock-3.18.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\labp4e001\downloads\.venv\lib\site-packages (from transformers) (25.0)
Collecting pyyaml>=5.1 (from transformers)
  Downloading PyYAML-6.0.2-cp312-cp312-win_amd64.whl.metadata (2.1 kB)
Collecting regex!=2019.12.17 (from transformers)
  Downloading regex-2024.11.6-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting requests (from transformers)
  Downloading requests-2.32.4-py3-none-any.whl.metadata (4.9 kB)
Collecting tokenizers<0.22,>=0.21 (from transformers)
  Downloading tokenizers-0.21.4-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
Collecting safetensors>=0.4.3 (from transformers)
  Downloading safetensors-0.5.3-cp38-abi3-win_amd64.whl.metadata (3.9 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub>=0.20.0->sentence-transformers)
  Downloading fsspec-2025.7.0-py3-none-any.whl.metadata (12 kB)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence-transformers)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch>=1.11.0->sentence-transformers)
  Downloading networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from torch>=1.11.0->sentence-transformers)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting setuptools (from torch>=1.11.0->sentence-transformers)
  Downloading setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: colorama in c:\users\labp4e001\downloads\.venv\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Collecting MarkupSafe>=2.0 (from jinja2->torch>=1.11.0->sentence-transformers)
  Downloading MarkupSafe-3.0.2-cp312-cp312-win_amd64.whl.metadata (4.1 kB)
Collecting charset_normalizer<4,>=2 (from requests->transformers)
  Downloading charset_normalizer-3.4.2-cp312-cp312-win_amd64.whl.metadata (36 kB)
Collecting idna<4,>=2.5 (from requests->transformers)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->transformers)
  Downloading urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->transformers)
  Downloading certifi-2025.7.14-py3-none-any.whl.metadata (2.4 kB)
Collecting joblib>=1.2.0 (from scikit-learn->sentence-transformers)
  Downloading joblib-1.5.1-py3-none-any.whl.metadata (5.6 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn->sentence-transformers)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading rank_bm25-0.2.2-py3-none-any.whl (8.6 kB)
Downloading sentence_transformers-5.0.0-py3-none-any.whl (470 kB)
Downloading transformers-4.54.0-py3-none-any.whl (11.2 MB)
   ---------------------------------------- 0.0/11.2 MB ? eta -:--:--
   --------------------------- ------------ 7.6/11.2 MB 36.2 MB/s eta 0:00:01
   ---------------------------------------- 11.2/11.2 MB 29.1 MB/s eta 0:00:00
Downloading huggingface_hub-0.34.2-py3-none-any.whl (558 kB)
   ---------------------------------------- 0.0/558.8 kB ? eta -:--:--
   ---------------------------------------- 558.8/558.8 kB 6.3 MB/s eta 0:00:00
Downloading tokenizers-0.21.4-cp39-abi3-win_amd64.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ------------------------- -------------- 1.6/2.5 MB 6.5 MB/s eta 0:00:01
   ------------------------------------- -- 2.4/2.5 MB 6.4 MB/s eta 0:00:01
   ---------------------------------------- 2.5/2.5 MB 5.1 MB/s eta 0:00:00
Downloading faiss_cpu-1.11.0.post1-cp312-cp312-win_amd64.whl (14.9 MB)
   ---------------------------------------- 0.0/14.9 MB ? eta -:--:--
   --------------------------------- ------ 12.3/14.9 MB 59.4 MB/s eta 0:00:01
   ---------------------------------------  14.7/14.9 MB 61.6 MB/s eta 0:00:01
   ---------------------------------------- 14.9/14.9 MB 32.3 MB/s eta 0:00:00
Downloading numpy-2.3.2-cp312-cp312-win_amd64.whl (12.8 MB)
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------  12.6/12.8 MB 65.5 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.8 MB 65.5 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.8 MB 65.5 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.8 MB 65.5 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.8 MB 65.5 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.8 MB 65.5 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.8 MB 65.5 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.8 MB 65.5 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.8 MB 65.5 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 6.5 MB/s eta 0:00:00
Downloading fsspec-2025.7.0-py3-none-any.whl (199 kB)
Downloading PyYAML-6.0.2-cp312-cp312-win_amd64.whl (156 kB)
Downloading regex-2024.11.6-cp312-cp312-win_amd64.whl (273 kB)
Downloading safetensors-0.5.3-cp38-abi3-win_amd64.whl (308 kB)
Downloading torch-2.7.1-cp312-cp312-win_amd64.whl (216.1 MB)
   ---------------------------------------- 0.0/216.1 MB ? eta -:--:--
   -- ------------------------------------- 13.6/216.1 MB 65.9 MB/s eta 0:00:04
   ----- ---------------------------------- 28.6/216.1 MB 67.1 MB/s eta 0:00:03
   ------- -------------------------------- 42.2/216.1 MB 67.1 MB/s eta 0:00:03
   ---------- ----------------------------- 56.1/216.1 MB 67.4 MB/s eta 0:00:03
   ------------ --------------------------- 68.2/216.1 MB 65.9 MB/s eta 0:00:03
   -------------- ------------------------- 81.0/216.1 MB 65.4 MB/s eta 0:00:03
   ----------------- ---------------------- 95.2/216.1 MB 66.0 MB/s eta 0:00:02
   ------------------- ------------------- 110.1/216.1 MB 66.3 MB/s eta 0:00:02
   ---------------------- ---------------- 124.5/216.1 MB 66.8 MB/s eta 0:00:02
   ------------------------- ------------- 139.5/216.1 MB 67.0 MB/s eta 0:00:02
   --------------------------- ----------- 154.9/216.1 MB 67.3 MB/s eta 0:00:01
   ------------------------------ -------- 168.6/216.1 MB 67.3 MB/s eta 0:00:01
   --------------------------------- ----- 183.2/216.1 MB 67.3 MB/s eta 0:00:01
   ----------------------------------- --- 197.7/216.1 MB 67.6 MB/s eta 0:00:01
   --------------------------------------  212.9/216.1 MB 67.7 MB/s eta 0:00:01
   --------------------------------------  216.0/216.1 MB 67.7 MB/s eta 0:00:01
   --------------------------------------  216.0/216.1 MB 67.7 MB/s eta 0:00:01
   --------------------------------------  216.0/216.1 MB 67.7 MB/s eta 0:00:01
   --------------------------------------  216.0/216.1 MB 67.7 MB/s eta 0:00:01
   --------------------------------------  216.0/216.1 MB 67.7 MB/s eta 0:00:01
   --------------------------------------  216.0/216.1 MB 67.7 MB/s eta 0:00:01
   --------------------------------------  216.0/216.1 MB 67.7 MB/s eta 0:00:01
   --------------------------------------  216.0/216.1 MB 67.7 MB/s eta 0:00:01
   --------------------------------------  216.0/216.1 MB 67.7 MB/s eta 0:00:01
   --------------------------------------  216.0/216.1 MB 67.7 MB/s eta 0:00:01
   --------------------------------------  216.0/216.1 MB 67.7 MB/s eta 0:00:01
   --------------------------------------- 216.1/216.1 MB 38.4 MB/s eta 0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   ---------------------------------------- 6.3/6.3 MB 29.7 MB/s eta 0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
   ---------------------------------------- 536.2/536.2 kB 4.4 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Downloading typing_extensions-4.14.1-py3-none-any.whl (43 kB)
Downloading filelock-3.18.0-py3-none-any.whl (16 kB)
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading MarkupSafe-3.0.2-cp312-cp312-win_amd64.whl (15 kB)
Downloading networkx-3.5-py3-none-any.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 18.9 MB/s eta 0:00:00
Downloading pillow-11.3.0-cp312-cp312-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------  6.8/7.0 MB 69.7 MB/s eta 0:00:01
   ---------------------------------------- 7.0/7.0 MB 30.7 MB/s eta 0:00:00
Downloading requests-2.32.4-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.2-cp312-cp312-win_amd64.whl (105 kB)
Downloading idna-3.10-py3-none-any.whl (70 kB)
Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
Downloading certifi-2025.7.14-py3-none-any.whl (162 kB)
Downloading scikit_learn-1.7.1-cp312-cp312-win_amd64.whl (8.7 MB)
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------  8.7/8.7 MB 77.0 MB/s eta 0:00:01
   ---------------------------------------- 8.7/8.7 MB 36.2 MB/s eta 0:00:00
Downloading joblib-1.5.1-py3-none-any.whl (307 kB)
Downloading scipy-1.16.1-cp312-cp312-win_amd64.whl (38.5 MB)
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   --------------- ------------------------ 14.7/38.5 MB 71.0 MB/s eta 0:00:01
   ------------------------------ --------- 29.6/38.5 MB 69.6 MB/s eta 0:00:01
   ---------------------------------------  38.3/38.5 MB 71.6 MB/s eta 0:00:01
   ---------------------------------------  38.3/38.5 MB 71.6 MB/s eta 0:00:01
   ---------------------------------------  38.3/38.5 MB 71.6 MB/s eta 0:00:01
   ---------------------------------------  38.3/38.5 MB 71.6 MB/s eta 0:00:01
   ---------------------------------------  38.3/38.5 MB 71.6 MB/s eta 0:00:01
   ---------------------------------------- 38.5/38.5 MB 23.1 MB/s eta 0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading setuptools-80.9.0-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 1.2/1.2 MB 8.5 MB/s eta 0:00:00
Installing collected packages: mpmath, urllib3, typing_extensions, tqdm, threadpoolctl, sympy, setuptools, safetensors, regex, pyyaml, Pillow, numpy, networkx, MarkupSafe, joblib, idna, fsspec, filelock, charset_normalizer, certifi, scipy, requests, rank_bm25, jinja2, faiss-cpu, torch, scikit-learn, huggingface-hub, tokenizers, transformers, sentence-transformers

   ----------------------------------------  0/31 [mpmath]
   ----------------------------------------  0/31 [mpmath]
   ----------------------------------------  0/31 [mpmath]
   ----------------------------------------  0/31 [mpmath]
   ----------------------------------------  0/31 [mpmath]
   ----------------------------------------  0/31 [mpmath]
   ----------------------------------------  0/31 [mpmath]
   ----------------------------------------  0/31 [mpmath]
   ----------------------------------------  0/31 [mpmath]
   ----------------------------------------  0/31 [mpmath]
   ----------------------------------------  0/31 [mpmath]
   ----------------------------------------  0/31 [mpmath]
   - --------------------------------------  1/31 [urllib3]
   - --------------------------------------  1/31 [urllib3]
   - --------------------------------------  1/31 [urllib3]
   - --------------------------------------  1/31 [urllib3]
   -- -------------------------------------  2/31 [typing_extensions]
   --- ------------------------------------  3/31 [tqdm]
   --- ------------------------------------  3/31 [tqdm]
   --- ------------------------------------  3/31 [tqdm]
   --- ------------------------------------  3/31 [tqdm]
   ----- ----------------------------------  4/31 [threadpoolctl]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]
   ------ ---------------------------------  5/31 [sympy]

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LabP4E001\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LabP4E001\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

# Implementación de la arquitectura.

## 1. Preprocesamiento del corpus

In [ ]:
! pip install pandas

Collecting pandas
  Downloading pandas-2.3.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\labp4e001\downloads\.venv\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\labp4e001\downloads\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\labp4e001\downloads\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.1-cp312-cp312-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   -------------------- ------------------- 5.8/11.0 MB 44.0 MB/s eta 0:00:01
   ----------------------- ---------------- 6.6/11.0 MB 17.5 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 18.7 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 14.9 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pandas

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed pandas-2.3.1 pytz-2025.2 tzdata-2025.2

In [ ]:
def contar_documentos(path):
    with open(path, 'r', encoding='utf-8') as f:
        total = sum(1 for _ in f)
    return total

ruta = 'arxiv-metadata-oai-snapshot.json'
total_docs = contar_documentos(ruta)
print(f"El archivo contiene {total_docs} documentos.")

El archivo contiene 2792339 documentos.

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LabP4E001\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\LabP4E001\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LabP4E001\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
import json
import string
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Agregar la ruta donde NLTK guardó los datos
nltk.data.path.append(r'C:\Users\LabP4E001\AppData\Roaming\nltk_data')

stop_words = set(stopwords.words('english'))

def preprocess(text):
    text = text.lower().translate(str.maketrans('', '', string.punctuation))
    tokens = word_tokenize(text)
    tokens = [w for w in tokens if w not in stop_words]
    return ' '.join(tokens)

def load_corpus(path, max_docs=28000):
    corpus = []
    with open(path, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f):
            if i >= max_docs:
                break
            doc = json.loads(line)
            doc['text'] = preprocess(doc['title'] + ' ' + doc['abstract'])
            corpus.append(doc)
    return corpus

corpus = load_corpus('arxiv-metadata-oai-snapshot.json')

### Mostrar en tabla el corpus

In [ ]:

import pandas as pd
import json
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))

def preprocess(text):
    text = text.lower().translate(str.maketrans('', '', string.punctuation))
    tokens = word_tokenize(text)
    tokens = [w for w in tokens if w not in stop_words]
    return ' '.join(tokens)

# Carga de corpus con textos originales y preprocesados
def load_corpus_for_display(path, max_docs=10):
    original = []
    procesado = []
    with open(path, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f):
            if i >= max_docs:
                break
            doc = json.loads(line)
            title = doc.get('title', '')
            abstract = doc.get('abstract', '')
            combined_text = title + ' ' + abstract
            original.append(combined_text)
            procesado.append(preprocess(combined_text))
    return pd.DataFrame({
        "Texto original": original,
        "Texto preprocesado": procesado
    })

df_corpus_display = load_corpus_for_display("arxiv-metadata-oai-snapshot.json", max_docs=10)
df_corpus_display.head(10)

,Texto original,Texto preprocesado
0,Calculation of prompt diphoton production cros...,calculation prompt diphoton production cross s...
1,Sparsity-certifying Graph Decompositions We ...,sparsitycertifying graph decompositions descri...
2,The evolution of the Earth-Moon system based o...,evolution earthmoon system based dark matter f...
3,A determinant of Stirling cycle numbers counts...,determinant stirling cycle numbers counts unla...
4,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,dyadic lambdaalpha lambdaalpha paper show comp...
5,Bosonic characters of atomic Cooper pairs acro...,bosonic characters atomic cooper pairs across ...
6,Polymer Quantum Mechanics and its Continuum Li...,polymer quantum mechanics continuum limit rath...
7,Numerical solution of shock and ramp compressi...,numerical solution shock ramp compression gene...
8,"The Spitzer c2d Survey of Large, Nearby, Inste...",spitzer c2d survey large nearby insterstellar ...
9,"Partial cubes: structures, characterizations, ...",partial cubes structures characterizations con...

## 2. Indexación

### Modelo BM25

In [ ]:
from rank_bm25 import BM25Okapi

tokenized_corpus = [doc['text'].split() for doc in corpus]
bm25 = BM25Okapi(tokenized_corpus)

### Modelo TF–IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform([doc['text'] for doc in corpus])

###  Embeddings

In [ ]:
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode([doc['text'] for doc in corpus], show_progress_bar=True)
index_faiss = faiss.IndexFlatL2(embeddings.shape[1])
index_faiss.add(np.array(embeddings))

c:\Users\LabP4E001\Downloads\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\LabP4E001\Downloads\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\LabP4E001\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Batches:   0%|          | 0/875 [00:00<?, ?it/s]c:\Users\LabP4E001\Downloads\.venv\Lib\site-packages\torch\nn\modules\module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
Batches: 100%|██████████| 875/875 [12:59<00:00,  1.12it/s]

## 3. Recuperacion

### TF-IDF

In [ ]:
def search_tfidf(query, top_k=10):
    query_vec = tfidf_vectorizer.transform([preprocess(query)])
    scores = tfidf_matrix.dot(query_vec.T).toarray().ravel()
    top_indices = scores.argsort()[::-1][:top_k]
    return [corpus[i] for i in top_indices]

### BM25

In [ ]:

def search_bm25(query, top_k=10):
    tokens = preprocess(query).split()
    scores = bm25.get_scores(tokens)
    top_indices = np.argsort(scores)[::-1][:top_k]
    return [corpus[i] for i in top_indices]

### Indice vectorial usando FAISS

In [ ]:

def search_faiss(query, top_k=10):
    vec = model.encode([preprocess(query)])
    scores, indices = index_faiss.search(np.array(vec), top_k)
    return [corpus[i] for i in indices[0]]

## 4. RAG

In [ ]:
from transformers import pipeline
rag_pipeline = pipeline("text2text-generation", model="google/flan-t5-base")

def generate_rag_response(query, top_k=3):
    top_docs = search_faiss(query, top_k)
    context = " ".join([doc['abstract'] for doc in top_docs])
    prompt = f"Query: {query}\nContext: {context}\nAnswer:"
    response = rag_pipeline(prompt, max_length=256)[0]['generated_text']
    return response

c:\Users\LabP4E001\Downloads\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\LabP4E001\.cache\huggingface\hub\models--google--flan-t5-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Device set to use cpu

In [ ]:
query = "machine learning for particle physics"
respuesta = generate_rag_response(query)
print("Respuesta generada con RAG:\n", respuesta)

Both `max_new_tokens` (=256) and `max_length`(=256) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Respuesta generada con RAG:
 A modified narrow-width approximation that allows for O(Gamma/M)-accurate predictions for resonant particle decay with similar intermediate masses is proposed and applied to MSSM processes to demonstrate its importance for searches for particle physics beyond the Standard Model. We explain how fluctuations of ratios can constrain and falsify the statistical model of particle production in heavy ion collisions, using $K/pi$ fluctuations as an example. We define an observable capable of determining which statistical model, if any, governs freeze-out in ultrarelativistic heavy ion collisions, using $K/pi$ fluctuations as an example. We calculate this observable for $K/pi$ fluctuations, and show that it should be the same for RHIC and LHC energies, as well as independent of centrality, if the Grand-Canonical statistical model is an appropriate description and chemical equilibrium applies. We also introduce a similar observable capable, together with the published $K*/K$ measurement, of ascertaining if an interacting hadron gas phase governs the system between thermal and

## 5. Evaluación

### Comparación de resultados

In [ ]:
def compare_top10_ids(query):
    tfidf_ids = [doc['id'] for doc in search_tfidf(query)]
    bm25_ids = [doc['id'] for doc in search_bm25(query)]
    faiss_ids = [doc['id'] for doc in search_faiss(query)]

    common_ids = {
        'TF-IDF ∩ BM25': list(set(tfidf_ids) & set(bm25_ids)),
        'TF-IDF ∩ FAISS': list(set(tfidf_ids) & set(faiss_ids)),
        'BM25 ∩ FAISS': list(set(bm25_ids) & set(faiss_ids)),
        'Todos en común': list(set(tfidf_ids) & set(bm25_ids) & set(faiss_ids))
    }

    return {
        'TF-IDF': tfidf_ids,
        'BM25': bm25_ids,
        'FAISS': faiss_ids,
        'Coincidencias': common_ids
    }

# Ejemplo de uso
query = "machine learning for particle physics"
resultados = compare_top10_ids(query)
print("Coincidencias entre modelos:\n", resultados['Coincidencias'])

Coincidencias entre modelos:
 {'TF-IDF ∩ BM25': ['0708.1564', '0704.3453', '0704.3905'], 'TF-IDF ∩ FAISS': [], 'BM25 ∩ FAISS': ['0707.0930'], 'Todos en común': []}

### Medir similitud entre ranking

In [ ]:
def show_rag_context_and_answer(query):
    top_docs = search_faiss(query, top_k=3)
    print("Títulos de documentos recuperados:")
    for i, doc in enumerate(top_docs):
        print(f"{i+1}. {doc['title']}")

    print("\nResumen combinado (contexto):")
    for doc in top_docs:
        print("- ", doc['abstract'][:300], "...\n")

    respuesta = generate_rag_response(query)
    print("\n Respuesta generada por RAG:\n", respuesta)

show_rag_context_and_answer("machine learning for particle physics")

Títulos de documentos recuperados:
1. A threshold-improved narrow-width approximation for BSM physics
2. What can we learn from fluctuations of particle ratios?
3. Bayesian Learning of Neural Networks for Signal/Background
  Discrimination in Particle Physics

Resumen combinado (contexto):
-    A modified narrow-width approximation that allows for O(Gamma/M)-accurate
predictions for resonant particle decay with similar intermediate masses is
proposed and applied to MSSM processes to demonstrate its importance for
searches for particle physics beyond the Standard Model.
 ...

-    We explain how fluctuations of ratios can constrain and falsify the
statistical model of particle production in heavy ion collisions, using $K/\pi$
fluctuations as an example. We define an observable capable of determining
which statistical model, if any, governs freeze-out in ultrarelativistic he ...

-    Neural networks are used extensively in classification problems in particle
physics research. Since the training of neural networks can be viewed as a
problem of inference, Bayesian learning of neural networks can provide more
optimal and robust results than conventional learning methods. We have
 ...

Both `max_new_tokens` (=256) and `max_length`(=256) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

 Respuesta generada por RAG:
 A modified narrow-width approximation that allows for O(Gamma/M)-accurate predictions for resonant particle decay with similar intermediate masses is proposed and applied to MSSM processes to demonstrate its importance for searches for particle physics beyond the Standard Model. We explain how fluctuations of ratios can constrain and falsify the statistical model of particle production in heavy ion collisions, using $K/pi$ fluctuations as an example. We define an observable capable of determining which statistical model, if any, governs freeze-out in ultrarelativistic heavy ion collisions, using $K/pi$ fluctuations as an example. We calculate this observable for $K/pi$ fluctuations, and show that it should be the same for RHIC and LHC energies, as well as independent of centrality, if the Grand-Canonical statistical model is an appropriate description and chemical equilibrium applies. We also introduce a similar observable capable, together with the published $K*/K$ measurement, of ascertaining if an interacting hadron gas phase governs the system between thermal and

In [ ]:
def count_common_documents(query):
    tfidf_ids = set([doc['id'] for doc in search_tfidf(query)])
    bm25_ids = set([doc['id'] for doc in search_bm25(query)])
    faiss_ids = set([doc['id'] for doc in search_faiss(query)])

    inter_tfidf_bm25 = tfidf_ids & bm25_ids
    inter_tfidf_faiss = tfidf_ids & faiss_ids
    inter_bm25_faiss = bm25_ids & faiss_ids

    all_common = tfidf_ids & bm25_ids & faiss_ids

    return {
        "TF-IDF ∩ BM25": len(inter_tfidf_bm25),
        "TF-IDF ∩ FAISS": len(inter_tfidf_faiss),
        "BM25 ∩ FAISS": len(inter_bm25_faiss),
        "Todos": len(all_common)
    }

print("Cantidad de coincidencias: ")
print(count_common_documents(query))

Cantidad de coincidencias:
{'TF-IDF ∩ BM25': 3, 'TF-IDF ∩ FAISS': 0, 'BM25 ∩ FAISS': 1, 'Todos': 0}

### Calidad

In [ ]:
import pandas as pd
# Leer queries desde el archivo txt
with open("queries.txt", "r") as f:
    queries = [line.strip() for line in f.readlines() if line.strip()]

# Función para evaluar calidad de recuperación
def benchmark_models(queries):
    records = []
    for query in queries:
        tfidf_ids = set([doc["id"] for doc in search_tfidf(query)])
        bm25_ids = set([doc["id"] for doc in search_bm25(query)])
        faiss_ids = set([doc["id"] for doc in search_faiss(query)])

        records.append({
            "Query": query,
            "TF-IDF ∩ BM25": len(tfidf_ids & bm25_ids),
            "TF-IDF ∩ FAISS": len(tfidf_ids & faiss_ids),
            "BM25 ∩ FAISS": len(bm25_ids & faiss_ids),
            "Todos comunes": len(tfidf_ids & bm25_ids & faiss_ids)
        })
    return pd.DataFrame(records)

# Ejecutar el benchmark y mostrar la tabla
df_benchmark = benchmark_models(queries)
df_benchmark

c:\Users\LabP4E001\Downloads\.venv\Lib\site-packages\torch\nn\modules\module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

,Query,TF-IDF ∩ BM25,TF-IDF ∩ FAISS,BM25 ∩ FAISS,Todos comunes
0,diphoton production cross sections,9,4,3,3
1,quantum chromodynamics,8,4,4,4
2,higgs boson decay,8,2,4,2
3,machine learning for particle physics,3,0,1,0
4,top quark production,5,5,5,3